[package]
name = "markdown-walker"
version = "0.0.2"
edition = "2021"
license = "MIT"
description = "A markdown walker trait for the comrak crate"

[dependencies]
comrak = { version = "0.32.0", features = ["emojis", "shortcodes"] }
